apiVersion: vault.gauchoracing.com/v1alpha1
kind: VaultSecretSync
metadata:
  name: example
  namespace: default
spec:
  serviceAccountName: default
  target:
    name: example-vault-secret
  secrets:
    EXAMPLE_TOKEN: example.token
